module EmailConstants
  module MailType
    SEND_FACULTY_ACCOUNT_INFORMATION = 'SEND_FACULTY_ACCOUNT_INFORMATION'
    SEND_RESET_PASSWORD_EMAIL = 'SEND_RESET_PASSWORD_EMAIL'
    SEND_REFER_FRIEND_CONFIRM_EMAIL = "SEND_REFER_FRIEND_CONFIRM_EMAIL"
  end
end
