module EmailConstants
  module MailType
    SEND_FACULTY_ACCOUNT_INFORMATION = 'SEND_FACULTY_ACCOUNT_INFORMATION'
    SEND_RESET_PASSWORD_EMAIL = 'SEND_RESET_PASSWORD_EMAIL'
    SEND_REFER_FRIEND_CONFIRM_EMAIL = "SEND_REFER_FRIEND_CONFIRM_EMAIL"
    SEND_CLAIM_EMAIL_NOTI = 'SEND_CLAIM_EMAIL_NOTI'
    SEND_STUDENT_REDEEM_EMAIL = 'SEND_STUDENT_REDEEM_EMAIL'
    SEND_ADMIN_REDEEM_EMAIL = 'SEND_ADMIN_REDEEM_EMAIL'
  end
end
