module RedeemConstants
  module TransactionState
    REDEEM_TRANSACTION_STATE_NEW = 'REDEEM_TRANSACTION_STATE_NEW'
    REEEM_TRANSACTION_STATE_READY = 'REEEM_TRANSACTION_STATE_READY'
    REDEEM_TRANSACTION_STATE_CANCEL = 'REDEEM_TRANSACTION_STATE_CANCEL'
    REDEEM_TRANSACTION_STATE_DONE = 'REDEEM_TRANSACTION_STATE_DONE' 
    REDEEM_TRANSACTION_STATES = [REDEEM_TRANSACTION_STATE_NEW,
                                 REEEM_TRANSACTION_STATE_READY,
                                 REDEEM_TRANSACTION_STATE_DONE,
                                 REDEEM_TRANSACTION_STATE_CANCEL]
  end
end
