module RedeemConstants
  module TransactionState
    REDEEM_TRANSACTION_STATE_NEW = 'REDEEM_TRANSACTION_STATE_NEW'
    REDEEM_TRANSACTION_STATE_READY = 'REDEEM_TRANSACTION_STATE_READY'
    REDEEM_TRANSACTION_STATE_CANCEL = 'REDEEM_TRANSACTION_STATE_CANCEL'
    REDEEM_TRANSACTION_STATE_DONE = 'REDEEM_TRANSACTION_STATE_DONE' 
    REDEEM_TRANSACTION_STATES = [REDEEM_TRANSACTION_STATE_NEW,
                                 REDEEM_TRANSACTION_STATE_READY,
                                 REDEEM_TRANSACTION_STATE_DONE,
                                 REDEEM_TRANSACTION_STATE_CANCEL]
  end

  module ProductItem
    STATE_AVAILABLE = 'AVAILABLE'
    STATE_LOCKED = 'LOCKED'
    STATE_SOLD = 'SOLD'
  end

  module Action
    CANCEL_TRANSACTION = 'CANCEL_TRANSACTION'
    APPROVE_TRANSACTION = 'APPROVE_TRANSACTION'
    COMPLETE_TRANSACTION = 'COMPLETE_TRANSACTION'
  end
end
