module ReferFriendConstants
  REFER_FRIEND_STATE_WAITING = "REFER_FRIEND_STATE_WAITING"
  REFER_FRIEND_STATE_CONFIRM = "REFER_FRIEND_STATE_CONFIRM"
  REFER_FRIEND_STATE_SUCCEED = "REFER_FRIEND_STATE_SUCCEED"
  REFER_FRIEND_STATE_FAILED = "REFER_FRIEND_STATE_FAILED"

  REFER_FRIEND_STATES = [
    REFER_FRIEND_STATE_WAITING,
    REFER_FRIEND_STATE_CONFIRM,
    REFER_FRIEND_STATE_SUCCEED,
    REFER_FRIEND_STATE_FAILED
  ]
end
