default: &default
  toolbar:
    - bold italic | undo redo
simple:
  <<: *default
  menubar: false
  toolbar:
    - bold italic | undo redo
normal:
  <<: *default
  toolbar:
    - bold italic | undo redo | image
  plugins:
    - image
    - link
    - code
    - lists
  images_upload_url: '/uploader/image'

